### ISSUE TITLE
How to add a Swift package?

### ISSUE THREAD

**Issue by GanZhiXiong** [pqrs-org/ShowyEdge#26]
I guess the steps are as follows, but I don't know it later.
For example, add the AXSwift package:
1. Add the following code under packages in project-base.yml:
```yml
packages:
  AXSwift:
    url: https://github.com/tmandry/AXSwift
    from: 0.3.2
```
3. Add the following code under dependencies:
```yml
    dependencies:
      - package: AXSwift
```

What else needs to be executed after adding it, I am not sure, whether it needs to be regenerated with XcodeGen later.
